Add --noValidation and --noCache support for deploy command
serverless/components pull request #1017
Opened 2021-08-30 07:57 UTC by timqian

Add `--noValidation` and `--noCache` support for deploy command.

Screenshot
<img width="557" alt="Screen Shot 2021-08-30 at 3 36 17 PM" src="https://user-images.githubusercontent.com/5512552/131305821-926791bc-b562-4a8d-b0b9-a0f3cee7a471.png">

Related ticket: https://app.asana.com/0/1200011502754281/1200844911571325

2021-08-30 08:08 UTC, ole3021 requested changes

2021-08-30 08:08 UTC, ole3021 commented on src/cli/CLI.js
> +    console.log('注: 可以使用 --noValidation 跳过 YML 验证');
这里改为 

console.log(''); // 另起一行
 console.log('可以使用 --noValidation 跳过 serverless 应用配置校验');

2021-08-30 08:08 UTC, ole3021 commented on src/cli/commands-cn/help.js
> +    --force                  跳过缓存和 YML 验证
强制部署，跳过缓存和 serverless 应用校验

2021-08-30 08:08 UTC, ole3021 commented on src/cli/commands-cn/help.js
> +    --noValidation           跳过 YML 验证
跳过 serverless 应用校验

2021-08-30 08:08 UTC, ole3021 commented on src/cli/CLI.js
> +    console.log('注: 可以使用 --noValidation 跳过 YML 验证');
这里的 后面一个console 使用灰色展示。 并且与前面的内容通过换行区分就可以。 不用 ----

2021-08-30 08:19 UTC, timqian commented
New screenshot
<img width="574" alt="Screen Shot 2021-08-30 at 4 15 13 PM" src="https://user-images.githubusercontent.com/5512552/131308821-ec8188ef-78bb-46fa-ae26-531510cc64e1.png">

2021-08-31 06:13 UTC, zongUMR approved these changes

2021-08-31 08:34 UTC, merged