fix: customize command inputs
serverless/components pull request #809
Opened 2020-09-29 02:48 UTC by yugasun

When running command is not `deploy`, we can not reset `inputs` to `{}`, because customized commands may need to use `inputs` in `serverless.yml`.

2020-09-29 07:26 UTC, timqian commented on src/cli/commands-cn/utils.js
> -    instanceYaml.inputs = {};
This part looks intentional. @hkbarton Why are we resetting `inputs` to `{}` here?

2020-09-29 07:28 UTC, timqian commented
@yugasun What are the `customized commands` you mentioned that will make use of the `inputs` in `serverless.yml`.

2020-09-29 07:56 UTC, yugasun commented
@timqian For cynosdb component, use may need reset theire password, or some other configs, they just config it in `serverless.yml` and using `sls resetpwd` command.

2020-09-29 07:57 UTC, yugasun commented on src/cli/commands-cn/utils.js
> -    instanceYaml.inputs = {};
Maybe no need to reset `inputs` to `{}`, so customize command can use these `inputs` directly.

2020-09-29 09:19 UTC, yugasun commented
@timqian I guess @hkbarton resetting `inputs` to `{}` just want to prevent source code to upload by `inputs.src`, so I make `inputs.src` to `undefined`.

2020-10-06 14:39 UTC, hkbarton commented on src/cli/commands-cn/utils.js
> +    instanceYaml.inputs.src = undefined;
maybe let's do this:

```
if (!instanceYaml.inputs) {
   instanceYaml.inputs = {}
}
```

I don't think we should remove src for user, if in case use DO need put src in their commands' input. 

I think the problem here is we should check if inputs exist or not, and we should NOT rest it to `{}` if the `inputs` is given.

2020-10-06 14:39 UTC, hkbarton requested changes
see comment inline

2020-10-06 14:41 UTC, hkbarton commented on src/cli/commands-cn/utils.js
> +    instanceYaml.inputs.src = undefined;
by doing this we are simply sanitizing the inputs, not changing any data inside.

2020-10-12 12:13 UTC, yugasun commented on src/cli/commands-cn/utils.js
> +    instanceYaml.inputs.src = undefined;
But when run commands except `deploy` for example `remove`, if we pass `inputs.src` to it, this action will also do `upload task`, below is the relative code `src/instance.js` in npm module `@serverless/platform-client-china`:

```js
const run = async (sdk, method = {}, instanceData = {}, credentials = {}, options = {}) => {
  let instance = JSON.parse(JSON.stringify(instanceData));

  // Validate method
  if (!method) {
    throw new Error('A "method" argument is required');
  }

  // Validate instance
  instance = validateAndFormat(instance);

  // Run source hook and upload source, if "src" input is used...
  // Save original src to present neatly in Dashboard/clients, or this will be replaced by the S3 location by the functions below
  if (instance.inputs.src) {
    instance.inputs.srcOriginal = JSON.parse(JSON.stringify(instance.inputs.src));
  }
  instance.inputs.src = await preRunSrcHook(instance.inputs.src);

  let size;
  let uploadTask;
  if (instance.inputs.src && typeof instance.inputs.src === 'string') {
    // Process source code, or skip if not provided...
    const { src: source, uploadPromise: task, cosInfo: sourceCosInfo } = await preRunSrcUpload(
      sdk,
      instance.orgName,
      instance.inputs,
      options
    );
    if (options.debug) {
      console.debug(`the code will be uploaded to ${source}`);
    }
    instance.inputs.src = source;
    instance.inputs.sourceCosInfo = sourceCosInfo;
    uploadTask = task;
  }

  if (uploadTask) {
    await uploadTask;
    await api.instance.run(sdk, instance, method, credentials, options, size);
  } else {
    return api.instance.run(sdk, instance, method, credentials, options, size);
  }
  return null;
};
```

2020-10-12 12:22 UTC, hkbarton commented on src/cli/commands-cn/utils.js
> +    instanceYaml.inputs.src = undefined;
@zongUMR has put a fix in this PR https://github.com/serverlessinc/platform-cn/pull/107, we think the fix belongs to here

2020-10-12 12:23 UTC, hkbarton commented on src/cli/commands-cn/utils.js
> +    instanceYaml.inputs.src = undefined;
basically doing:
```
  if (instance.inputs.src && typeof instance.inputs.src === 'string' && method === 'deploy')  
```
in the code you pasted

2020-10-12 12:24 UTC, hkbarton commented on src/cli/commands-cn/utils.js
> +    instanceYaml.inputs.src = undefined;
and the rule of here is don't mutate user's inputs

2020-10-12 14:52 UTC, yugasun commented on src/cli/commands-cn/utils.js
> +    instanceYaml.inputs.src = undefined;
Well, if your [serverlessinc/platform-cn#107](https://github.com/serverlessinc/platform-cn/pull/107) have been merged, I will close this PR.

2020-10-13 13:42 UTC, closed without merging