remove org
serverless/components pull request #887
Opened 2021-02-09 05:24 UTC by ole3021

## What has been implemented?

Remove org from China Readme File as the `org` is not used in China Platform

## Steps to verify

[None]

## Todos:

[None]

2021-02-09 07:19 UTC, timqian requested changes

2021-02-09 07:19 UTC, timqian commented on README.cn.md
> +  name: ${stage}-${app}-${name} # 命名最终为 "acme-prod-ecommerce-rest-api"
`命名最终为 "prod-ecommerce-rest-api"`

2021-02-18 04:15 UTC, ole3021 commented on README.cn.md
> +  name: ${stage}-${app}-${name} # 命名最终为 "acme-prod-ecommerce-rest-api"
已修正

2021-02-18 05:26 UTC, timqian approved these changes

2021-02-19 01:58 UTC, merged