fix: check invalid inline comments in env file
serverless/components pull request #898
Opened 2021-03-01 07:27 UTC by zongUMR

## What has been implemented?

Closes https://github.com/serverless/roadmap-tencent/issues/787

Currently, the `dotenv` can not remove **inline comment** in the env file: https://github.com/motdotla/dotenv/issues/484, which will cause error when users use inline comments. This PR will check this situation and throw an message.

## Steps to verify

- Run X
- ...

## Todos:

- [ ] Write tests
- [ ] Write / update documentation
- [ ] Run Prettier

2021-03-01 08:25 UTC, ole3021 requested changes

2021-03-01 08:25 UTC, ole3021 commented on src/cli/index.js
> +          cli.log(`${key}的值为:${envValue}, 含有不正确内容，请修改后重试(不支持行内注释)`, 'red');
这里有几个问题

* 如果本身的环境变量的值就是带有`#`字符的话，这样处理会产生误会。比如`account=some#sec$re*Id`, 这里 `#`  并不是注释的含义。
* 另外不应该显示用户的环境变量值在log中，因为比如用户配置的是secret，但是因为最最后加入了注释，导致解析失败，会导致这一条log会被系统日志收集，增加了secret暴露的风险。 

建议只修改当前的提示信息清晰提示用户所传的值无效，而不是没有值 就可以了。

2021-03-01 08:25 UTC, ole3021 commented on src/cli/index.js
> +          cli.log(`${key}的值为:${envValue}, 含有不正确内容，请修改后重试(不支持行内注释)`, 'red');
@zongUMR

2021-03-01 08:48 UTC, zongUMR commented on src/cli/index.js
> +          cli.log(`${key}的值为:${envValue}, 含有不正确内容，请修改后重试(不支持行内注释)`, 'red');
1. I mentioned this concern in my comment above, so how we should check the value here? In the normal `.env` file, syntax will say ` #xxxxx` is a comment(**a space before the #symbol**), should we use the same rule? 
2. Agreed, will update it.

2021-03-01 09:32 UTC, ole3021 commented on src/cli/index.js
> +          cli.log(`${key}的值为:${envValue}, 含有不正确内容，请修改后重试(不支持行内注释)`, 'red');
>     1. concern

1. The issue I think is `The secretId is not found, please ensure that your secret id is correct.`

This may confuse the user that either the .env file works and why the secretId is not found (actually it is incorrect.)

The root cause of this issue is that the use not understand for dotenv, the comment should start with a new line with #. 

For the solution, I think we can do 

* Fix the error message, make it clear that the value is incorrect instead of key's value not found.  eg:`环境变量${key}的值无效，请核对后重试。`
* Furthermore, if we can identify the value of .env file is incorrect, we can do extra check if there have `#` with several spaces before it and show the warning message eg: `在dotenv配置中发现 #,请确保注释都写在单独由#开头的一行。详情查看：https://github.com/motdotla/dotenv#rules`

2021-03-01 10:22 UTC, zongUMR commented on src/cli/index.js
> +          cli.log(`${key}的值为:${envValue}, 含有不正确内容，请修改后重试(不支持行内注释)`, 'red');
1. Use warning message to alert users
2. Do not exit process
<img width="1233" alt="Screen Shot 2021-03-01 at 18 22 34" src="https://user-images.githubusercontent.com/11454175/109484196-1bdeee80-7abb-11eb-87b5-d61841c6127e.png">

2021-03-02 09:05 UTC, ole3021 approved these changes

2021-03-02 10:21 UTC, medikoo submitted a review, later dismissed
Looks good to me 👍

2021-03-02 12:04 UTC, merged