Check latest components version and ask users to upgrade
serverless/components pull request #917
Opened 2021-03-25 06:09 UTC by timqian

> https://app.asana.com/0/1200011502754281/1200090410758582

## What has been implemented?

Check latest Components version and recommand users to upgrade if they are using older version

2021-03-25 07:08 UTC, zongUMR commented
@timqian I agree that we need to only notify user to update CLI by `npm -g i serverless`, just like the npm, and here is another package: [update-notifer](https://www.npmjs.com/package/update-notifier) which can output the info directly.

2021-03-25 07:12 UTC, timqian commented
@zongUMR Thanks for the note! directly using `update-notifer` looks like a better option

2021-03-25 08:10 UTC, medikoo requested changes
For non China versions we already have upgrade notifications configured through backend notifications service. Technically same could be done in context of `platform-cn`.
Anyway I think it's ok to do it here, but only if it's applied to users in China (while as I see this functionality is run unconditionally for any users).

Also `npm install -g severless` is not guranteed to upgrade `@serverless/components` which is a dependency of `serverless`. Bulletproof would be `npm update -g serverless`.

Additionally notifier should only notify of minor upgrades. Note that `major` upgrades will in all cases be impossible that way (as `@serverless/components`  version in `serverless` is always pinned to specific major). In our backend notification service we have intelligence which ensures that user is notified about updates in major they're relying on(e.g. our current latest is v2, but we created one v1 release, and v1 users were notified about it, even though it's not _latest_ on npm grounds)

2021-03-29 03:22 UTC, timqian commented
@zongUMR @medikoo I have updated the PR a bit by using `[update-notifer](https://github.com/yeoman/update-notifier#how)`:

- [x] Whenever a Chinese user uses the CLI, it asynchronously checks with npm in the background for available updates and won't block 
- [x] Notification is shown to users one time a day at most, this is done to not be annoying to the user
- [x] Notification will be shown when there is `major`, `minor`, or `patch` upgrades
- [x] Notification preview

<img width="668" alt="Screen Shot 2021-03-29 at 11 14 36 AM" src="https://user-images.githubusercontent.com/5512552/112782598-f7f1d700-907f-11eb-91b0-5b34d241a8fb.png">

2021-03-29 09:43 UTC, medikoo reviewed
@timqian looks good, I've proposed to addd just one minor optimization for non-china users

2021-03-29 09:43 UTC, medikoo commented on src/cli/index.js
> +const updateNotifier = require('update-notifier');
Let's require it only when it's used, so let's put it into that `if block

2021-03-29 10:16 UTC, medikoo approved these changes
Thanks @timqian looks good

2021-03-30 02:55 UTC, zongUMR approved these changes

2021-03-30 08:10 UTC, ole3021 commented
Sorry for responding late,  As we just researched the notification features, and if we don't implement the update automatically in the background.  I think we need to consider the two options below. 

Option A: Implement in this PR. 
* Implement on the CLI side, and show a message for users to update to the latest version. 

Option B: Use the notificaiton.
* Implement on the Server-side (sls-metrics), and show a message only after use deploy and under a specific version. 

I prefer to go with the Option B:
* The CLI implementation is not working for older versions, but the notification will. 
* we don't need to ask user to update for each patch version release.
* we better check the version for `serverless/cli` and `serverless/components` separately. 

@timqian  @zongUMR  @medikoo  ^

2021-03-30 08:13 UTC, medikoo commented
> I prefer to go with the Option B:

I agree, it gives better control and also works for older version.

You may take an inspiration from `@serverlessinc/platform` repo, on how this notification is resolved there (If you lack access I'll be happy to expose needed files)

2021-03-30 08:50 UTC, timqian commented
I agree, notifying users using older versions is definitely better. I will take a look at the `platform` code and try to add it to `platform-cn`

2021-04-01 07:39 UTC, ole3021 commented
Close the CLI change for update warning, will use the notification feature to show user update warning messages.

2021-04-01 07:39 UTC, closed without merging