Better cli logs
serverless/components pull request #923
Opened 2021-03-31 13:09 UTC by timqian

## What has been implemented?

- https://app.asana.com/0/1200011502754281/1200096501801115
- https://app.asana.com/0/1200011502754281/1200096501801123

2021-04-01 06:30 UTC, ole3021 requested changes

2021-04-01 06:30 UTC, ole3021 commented on src/cli/commands-cn/init.js
> +        '需要指定 Component 或者 Template 的名称 e.g. "serverless init scf-starter".'
请指定 component 或 template 名称，如：“serverless init scf-starter”。

2021-04-01 06:30 UTC, ole3021 commented on src/cli/commands-cn/run.js
> +    if (instance.outputs.apigw && instance.outputs.apigw.url) {
这个我之前和meng 讨论了一下， 考虑后觉得还是不显示“项目访问地址”。 主要是因为

* apigateway： 不确定项目中会有多少个 apigateway， template以 fullstack为例 可能有多个，无法准确区分那个是 可访问的前端地址(实现需要更复杂逻辑)。
* apigateway 的地址不一定可以直接访问，有的是api地址，也可能是socket地址， 需要特定的调用方式才能使用。

如上，考虑还是不现实，这部分内容我会在文档中做进一步说明。 用户可以从文档获得相关知识。

2021-04-01 08:17 UTC, zongUMR approved these changes

2021-04-02 02:28 UTC, ole3021 approved these changes

2021-04-02 02:33 UTC, merged