Log command
serverless/components pull request #942
Opened 2021-05-04 04:02 UTC by timqian

Add `sls log` command

https://app.asana.com/0/1200011502754281/1200211330092190

2021-05-11 07:01 UTC, zongUMR requested changes

2021-05-13 02:25 UTC, timqian commented on src/cli/commands-cn/logs.js
> +  const client = new FaaS({
Yeah, login should be invoked before this line. Thanks for the note

2021-05-13 05:20 UTC, zongUMR commented
Should we judge if the current folder is a instance folder at first? We can only run `log` command insdie an instance project, right?

2021-05-13 05:22 UTC, zongUMR submitted a review, later dismissed

2021-05-14 08:19 UTC, zongUMR requested changes

2021-05-14 08:19 UTC, zongUMR commented on src/cli/commands-cn/logs.js
> +  await utils.checkBasicConfigValidation(instanceDir);
We should lift this logic at the first of this function

2021-05-14 08:20 UTC, zongUMR approved these changes

2021-05-14 09:18 UTC, zongUMR approved these changes

2021-05-17 03:14 UTC, zongUMR submitted a review, later dismissed

2021-05-17 03:15 UTC, zongUMR approved these changes

2021-05-17 06:54 UTC, merged