Improve component logic
serverless/components pull request #994
Opened 2021-07-15 04:32 UTC by zongUMR

1. If Chinese user is in component or template project, we just use components logic.
2. Add **--target** option for `dev` command
3. Check **path** validation

2021-07-15 08:13 UTC, medikoo requested changes
@zongUMR thanks for update. I've proposed some logic organization improvement.

Also it's not clear to me what use case this addresses (?)

In which case we currently do not load components, and after this change we will load them?

2021-07-15 08:13 UTC, medikoo commented on src/legacy.js
> +  if (isChinaUser() && (hasServerlessConfigFile(process.cwd()) || runningTemplate(process.cwd()))) {
It'll be nice if it's combined with conditional which now is at L45. So code goes as:

```javascript
if (isChinaUser()) {
 // China specific conditions
}
```

2021-07-15 08:14 UTC, zongUMR commented on src/legacy.js
> +  if (isChinaUser() && (hasServerlessConfigFile(process.cwd()) || runningTemplate(process.cwd()))) {
I will update it

2021-07-15 08:16 UTC, zongUMR commented
> @zongUMR thanks for update. I've proposed some logic organization improvement.
> 
> Also it's not clear to me what use case this addresses (?)
> 
> In which case we currently do not load components, and after this change we will load them?

Currently If we use `sls dev` inside a template project(https://github.com/serverless-components/tencent-examples/tree/master/fullstack), it will not load components

2021-07-15 08:19 UTC, medikoo commented
> Currently If we use sls dev inside a template project(https://github.com/serverless-components/tencent-examples/tree/master/fullstack), it will not load components

Is this specific just to `sls dev` command? If it's the case, maybe we could narrow condition so it applies just to that (?)

2021-07-15 08:21 UTC, zongUMR commented
> > Currently If we use sls dev inside a template project(https://github.com/serverless-components/tencent-examples/tree/master/fullstack), it will not load components
> 
> Is this specific just to `sls dev` command? If it's the case, maybe we could narrow condition so it applies just to that (?)

Actually not, we also have some other commands which should load components: `invoke`, `invoke local`, `logs` and future commands. This Tim's PR: https://github.com/serverless/components/pull/993, it will depend on this change as well

2021-07-15 08:27 UTC, zongUMR commented on src/legacy.js
> +  if (isChinaUser() && (hasServerlessConfigFile(process.cwd()) || runningTemplate(process.cwd()))) {
I combined those conditions for Chinese users

2021-07-15 09:25 UTC, medikoo requested changes
Thanks @zongUMR I see just one issue, otherwise it looks good

2021-07-15 09:25 UTC, medikoo commented on src/legacy.js
> +  // For Chinese users
This comment feels obsolete as code is self explanatory on that

2021-07-15 09:25 UTC, medikoo commented on src/legacy.js
> +    // Chinese users running "serverless deploy" in a project without a serverless config file
I would also remove this comment, as it code feels self explanatory

2021-07-15 09:25 UTC, medikoo commented on src/legacy.js
> +    if (hasServerlessConfigFile(process.cwd()) || runningTemplate(process.cwd())) {
I believe it should be just `if (runningTemplate(process.cwd()))`, otherwise we're introducing a breaking change for all AWS users in China, as it'll unconditionally run Components in context of Serverless Framework services

2021-07-15 09:31 UTC, zongUMR commented on src/legacy.js
> +  // For Chinese users
Fixed.

2021-07-15 09:31 UTC, zongUMR commented on src/legacy.js
> +    // Chinese users running "serverless deploy" in a project without a serverless config file
Fixed.

2021-07-15 09:31 UTC, zongUMR commented on src/legacy.js
> +    if (hasServerlessConfigFile(process.cwd()) || runningTemplate(process.cwd())) {
Agree, updated it

2021-07-15 10:02 UTC, medikoo requested changes
@zongUMR sorry for second thought, but I've noticed that template check is already made. Please see my comment

(note this check can be expensive, so it's better to not double that)

2021-07-15 10:02 UTC, medikoo commented on src/legacy.js
> +    if (runningTemplate(process.cwd())) {
I've looked closer, and we already have `runningTemplate` detection here.

It just additionally confirms that component command is used: https://github.com/serverless/components/blob/a8633ca7ed88a7919efe777860d5c10861ef4bd9/src/legacy.js#L32

I think best would be to simply update thise method, so also `dev` is recognized as component command

2021-07-15 10:05 UTC, zongUMR commented on src/legacy.js
> +    if (runningTemplate(process.cwd())) {
But if we have more commands later, we must add them in `nestedTemplateKeywords`. For Chinese users, if they are in template, just need to load components I think.

2021-07-15 10:06 UTC, zongUMR commented on src/legacy.js
> +    if (runningTemplate(process.cwd())) {
And I also have a question, why we can not just use `runningTemplate`, and use `nestedTemplateKeywords` to limit the methods?

2021-07-15 10:08 UTC, medikoo commented on src/legacy.js
> +    if (runningTemplate(process.cwd())) {
As this check expensive we decided to imply that check only if used command is recognized as component command.
And same problem applies if user is in China, I believe same rule should be followed in case of Chines version.

Not this check does recursive deep dir read, which in directory with big structure may turn to be time-taking.

2021-07-15 10:08 UTC, medikoo requested changes
As this check  is expensive we decided to imply that check only if used command is recognized as component command.
And as same problem applies if user is in China, same rule should be followed

Note this check does recursive deep dir read, which in directory with big structure may turn to be time-taking.

2021-07-15 10:09 UTC, medikoo commented on src/legacy.js
> +    if (runningTemplate(process.cwd())) {
> and use nestedTemplateKeywords to limit the methods?

What do you mean by that?

2021-07-15 10:11 UTC, zongUMR commented on src/legacy.js
> +    if (runningTemplate(process.cwd())) {
I mean we use `nestedTemplateKeywords` to limit only those methods in **template project** will load components, right?

2021-07-15 10:14 UTC, medikoo commented on src/legacy.js
> +    if (runningTemplate(process.cwd())) {
`nestedTemplateKeywords ` is the list of component commands that can be used for template projects.

So first we validate if given command applies to template project, and only having that confirmed we check whether we are in template project (and that check in some edge scenarios may lock the process for a while)

2021-07-15 10:29 UTC, zongUMR commented on src/legacy.js
> +    if (runningTemplate(process.cwd())) {
So, your suggestion is that we do not change the logic here, only update `nestedTemplateKeywords` with the new commands we want to run in template?

2021-07-15 10:35 UTC, medikoo commented on src/legacy.js
> +    if (runningTemplate(process.cwd())) {
> So, your suggestion is that we do not change the logic here, only update nestedTemplateKeywords with the new commands we want to run in template?

yes, exactly

2021-07-15 10:54 UTC, zongUMR commented on src/legacy.js
> +    if (runningTemplate(process.cwd())) {
In this respect. I agree with this view. @ole3021 How do you think about it?

2021-07-15 10:56 UTC, ole3021 commented
@medikoo  Thanks for the update about the logic, and the story behind this is 

* currently we are adding more commands into Serverless Tencent, as `invoke`, `invoke local` and `logs` and we are build the feature to support those commands from the template folder.  (as the template folder is a set of components).
    * Without the support of those commands from template folder, when user do multi components development, user needs to go to each compoents folder to using the commands, which is not a good experience for developers, as it distract users from their own code and logic. 
* Users also complained about the behave different in template folder when execute some Serverless Tencent commands, as except all the commands are handled by the Serverless Traditional. (and user dont have a good understanding about components and template.)
    * also we have a command not support chinese warning message for users when they execute some non exist commands, but this never works in template folder. 

* Also based on the discussion we aligned earlier, we will keep the Serverless Traditional for users in China as default and for the traditional projects by default. (without set the vendor in ENV)

I think compares to add those new commands in the support list, its better to handle the template folder with Serverless Tencent instead. 

If it is only the performance issue block us to do so, can we change the improve the logic about checking if a folder is a Template Folder? and here are my suggestions.

## solution A : Improve the template check

> A template folder should be a folder have `serverlss.yml` with only common fields (no component, no inputs, no functions.) And at least a sub components folder in it (have serverless.yml and include component field.)

so can we check as the follow process
1. if current folder have `serverless.yml` with out fields (components, inputs, function)
   * [yes] go step 2
   * [no] false
2. get the nest folders in current folder. (move probably system folder to the last , eg .git, node_modules etc)
3. check nest folder one by one, if have serverless.yml and if there have component exist
   * [yes] true 
   * [no] go 3
   * [chkeck all the nest folders] go 4
4. false.

or even simpler
Just check if current folder have `serverless.yml` (true) and no fields in it (components, inputs, functions, etc), then consider it as a template folder.

## Solution B : Replace check a folder is template , check a folder is traditional.

> as China users use Serverless Traditional is not much, instead so spending time verify if a folder is template, we can check if a folder is Traditional instead. 

Here are the logic in detail. 

isChinaUser: true (User from China)
* If current folder has no serverless.yml.yaml.json.js etc, take it as the empty folder, and handls by Serverless Traditional by default. 
* If a folder has serverless.yml, and there have functions fields in it, handls it by Serverless Traditional as it is a traditional folder. 
* for the left are handles by Serverless Tencent. 

Please have a check , and im love to have future talk with you when you got tim.

2021-07-15 12:03 UTC, medikoo commented
@ole3021 thanks for explanations.

> I think compares to add those new commands in the support list, its better to handle the template folder with Serverless Tencent instead.

Yes, it's better to invoke _runningTemplate_ check only if we confirmed that we're in context of command that's supported by Components template project.

>If it is only the performance issue block us to do so, can we change the improve the logic about checking if a folder is a Template Folder?

Current implementation of this check I believe is as optimal as it can be. You can investigate it here:https://github.com/serverless/components/blob/a8633ca7ed88a7919efe777860d5c10861ef4bd9/src/cli/utils.js#L548-L578

I've check the options you list, but they seem to offer quite different resolution logic, that will actually change the detection and not optimise it.

Current rules that establish what is template project are as follows (all must be met):
- There's no service configuration (`serverless.yml` or similar) at root folder
- One of the child folders (of which name doesn't start with `.`) should have component configuration (so `serverless.yml` file or similar, which exports `component` property)
- There must be no child folder which contains Framework service configuration (it's to prevent situation where we mark as template, something as _Projects_ folder which may contain many different component projects and regular framework projects as well)

If you have suggestions how to better implement solutions that confirms on that rules, it's definitely welcome, but otherwise I think that those rules should not be changed

2021-07-16 03:19 UTC, ole3021 commented
@medikoo  thx for update the logic, and i do miss check the code before propose the solution. Here are the logic table for use cases (folder) and conditions below. The priority order is from left to right.

|                        | Non-SLS     | Components | Traditional | Template   | Other       |
| ---------------------- | ----------- | ---------- | ----------- | ---------- | ----------- |
| isChinaUser            | -           | true       | -           | true       | -           |
| root serverless.yml    | false       | true       | true        | true       | true        |
| field: components      | -           | true       | false       | false      | -           |
| field: services        | -           | -          | true        | false      | -           |
| > deployable           | -           | true       | true        | false      | -           |
|                        |             |            |             |            |             |
| nest serverless.yml    | -           | -          | -           | least 1    |             |
| nest field: components | -           |            |             | all true   | -           |
| nest field: services   | -           |            |             | all false  | -           |
|                        |             |            |             |            |             |
| use CLI                | traditional | components | traditional | components | traditional |
|                        |             |            |             |            |             |

true: means need to exist .
false: meens need to not exist.
-: means no need to consider

Base on the table above, i think the issue we are facing here is to tell template correctly from Other folders include serverless.

Then the logic `runningTemplate ` above only purpose is to tell template from other folders. 
if we can agree on this. i think we can do following changes to easy solve the issue with out heavy calculation. 

* if a serverless folder (include serverless) is not `deployable`.
    * Do not do nest folder calculation. 
    * Use components directly for China users, and keep traditional for non-China users.

So we can avoid the nest folder check, and for the template users case, it will work the same, but for the other user cases, changes will be 
* [isChinaUser] will show components error message and warnings.
* [other] will show traditional error message. 

Thats what we want to achieve.

2021-07-16 10:01 UTC, medikoo commented
@ole3021 Thanks for explanations.

If I understand above table correctly. The difference between _template_  project of AWS and of Tencent components. Is that AWS template project does not host root `serverless.yml`. While Tencent template project hosts it. Is that the case?

If so, what's the content of root `serverless.yml` in such case?

_Note: Otherwise I do not see any differences, and so far logic should work well (aside of fact that listed commands need to reflect also all commands that are supported in Tencent template projects_

2021-07-19 00:15 UTC, zongUMR commented
@ole3021 @medikoo I will only add new commands in `legacy.js` for this PR to enable it available. We can still discuss this topic in this thread, and we can improve this logic once we have a result

2021-07-19 02:47 UTC, timqian approved these changes
The current implementation looks good to me

2021-07-19 02:48 UTC, merged